// Stacks
export const FETCH_STACKS = "FETCH_STACKS"
export const FETCH_STACK = "FETCH_STACK"

// service
export const FETCH_SERVICES = "FETCH_SERVICES"
export const FETCH_SERVICE = "FETCH_SERVICE"
export const DELETE_SERVICE = "DELETE_SERVICE"
export const SET_DELETE_SERVICE = "SET_DELETE_SERVICE"

export const FETCH_TASK_BY_SERVICE_NAME = "FETCH_TASK_BY_SERVICE_NAME"

// Containers
export const FETCH_CONTAINERS = "FETCH_CONTAINERS"
export const FETCH_CONTAINER = "FETCH_CONTAINER"
export const PAUSE_CONTAINER = "PAUSE_CONTAINER"
export const UNPAUSE_CONTAINER = "UNPAUSE_CONTAINER"

// Images
export const FETCH_IMAGES = "FETCH_IMAGES"

// Volumes
export const FETCH_VOLUMES = "FETCH_VOLUMES"
export const FETCH_VOLUME = "FETCH_VOLUME"
